### ISSUE TITLE
Extended quick start help

### ISSUE THREAD

**Issue by Cicrocoft** [jlama/powertagd#10]
Hi,

I've given up on pairing my 3P R9 power tags trough a hue smart switch and z2m, and now trying your solution. 

I understand all the steps in the QuickStart guide, but step 2 "build powertagd with make". Could you "noobify" this step for me :-)?

Another question: What app do you use in HA to process the file it spits out, when everything is up and running? Was looking around in my influxDB addon, but failed to locate a locale file import.

**Comment by jlama** [comment]
To build, `cd` in the `src` directory and run `make`.

I don't use HA. `powertagd` simply outputs data to stdout, it doesn't create files. You need to process the output yourself or you can use the included `powertag2influx` app to send the data directly to InfluxDB.

Using `powertag2influx`, running `powertagd` would look something like:
```
powertagd | powertag2influx --token xxx --orgId xxx --bucket powertag
```

**Comment by Cicrocoft** [comment]
That simple 😂 Thanks. 

Great, then I can create a sensor from the influxDB entries, and everything will look shinny and nice. 

Will make a short how to, if/when I get it all working for future HA users. 

Thanks again.

**Comment by Seekersdk** [comment]
Getting stuck at this error: Makefile:33: ash.o Error 127. Tried giving chmod x permissions to the files also.

![image](https://user-images.githubusercontent.com/78330843/215909921-0d82d50a-36fc-4c47-a9bb-0ff985a53a1a.png)

Running Linux 5.15 64bit

Edit: Just saw it logged me on to my new account. Its still the same person writting... lol

**Comment by Cicrocoft** [comment]
Think I'll make a fresh Linux installation to test. Looks like it's a very reduced Linux installation HA runs on, so it's properly the issue.

**Comment by jlama** [comment]
The issue here is that you haven't any `cc` installed, i.e. a compiler. You need to install gcc or clang.

**Comment by Seekersdk** [comment]
Had to install gcc and alpine-sdk - Then it worked :) Thanks

Will flash dongle e now and see if it all works :)

**Comment by Seekersdk** [comment]
So, got the dongle flashed and running. Just need to fix the databse part now.
It says:

![image](https://user-images.githubusercontent.com/78330843/216022761-2b2262bd-7985-4f28-8571-9224798d8711.png)

Think I figured it out. Need to run the .go file in your git.. So for this I need Golang support in my HA container... Think I will end up installing this on a "clean and normal" Ubuntu installation instead of the container HA is running in.

**Comment by jlama** [comment]
You just need to install golang somewhere to build it, could be on any machine.

**Comment by Seekersdk** [comment]
Builded the influx file somewhere else, and move it to the HA system... then had to gcompat and libc6-compat, and I could run the file... So now im almost at the finish line I hope. Just need to add the USB dongle again, and link the database :)

apk add gcompat
apk add libc6-compat

![image](https://user-images.githubusercontent.com/78330843/216127292-52d72377-2bdc-44a7-90c6-a6697090f799.png)

Do I need to specify the path for the USB dongle for the powertagd part?
powertagd | powertag2influx --token xxx --orgId xxx --bucket powertag

**Comment by Seekersdk** [comment]
Got everything running finally... Just cant get the powertags to connect.

Powertag R9M63/R9M41

Getting this error:
![image](https://user-images.githubusercontent.com/78330843/216190177-bdda8452-0382-4775-bd51-b0b1db4fae26.png)

**Comment by jlama** [comment]
Weird. Seems like your PowerTag do some things differently.
Can you run with the -v flag and post the result (text format) please?

**Comment by Seekersdk** [comment]
sure - give me 10min. Need to install Putty. Was using the build in terminal in HA... it is very basic

**Comment by Seekersdk** [comment]
This Alpine linux, HA and me will never become friends.

Find below log - Let me know if it is enough :)
[putty2.log](https://github.com/jlama/powertagd/files/10563329/putty2.log)

**Comment by jlama** [comment]
Thanks, I'll take a look later, but at first glance your PowerTags use a completely different set of commissioning options.
I also have a R9M41 but it doesn't behave like this.

What is the Version number of your PowerTag? (It's on the PowerTag sticker, below the SN).

**Comment by Cicrocoft** [comment]
Lucky me 😂😩

Version: V004.000.424

**Comment by jlama** [comment]
So you have newer PowerTags than mines and they have changed how they are commissioned.

I've pushed some changes to the repo, please rebuild powertagd (rerun make), try again and let me know.

**Comment by Seekersdk** [comment]
There is a 90% chance it the Alpine linux being a annoyingthough, but just to confirm before I start adding stuff, is it me or you :P?

![image](https://user-images.githubusercontent.com/78330843/216334357-98695a93-9d87-46bb-978e-8b78ae75e47f.png)

**Comment by jlama** [comment]
You must be missing a package, like libc-dev.

**Comment by Seekersdk** [comment]
Success (I think?):

![image](https://user-images.githubusercontent.com/78330843/216336127-96ae0dce-45ac-492f-bdd5-a1e2cb1be0bf.png)

**Comment by jlama** [comment]
Yes!

**Comment by Seekersdk** [comment]
Fantastic :)

Now I just need to get the database part to work. Getting connection refused when trying to connect to influx...

**Comment by Seekersdk** [comment]
Added --url for the direct ip to the server. Now it works :-)

**Comment by Seekersdk** [comment]
Got it all running nice and smooth now. Thank you for helping a Linux newb, @jlama.

Note to HA users wanting to run this within the HA container: When you update the HA core, you will losse all the libraries etc you have installed, and you need to reinstall them. The powertagd files and powertag2influx is still there.

![image](https://user-images.githubusercontent.com/78330843/216373684-44a98e94-1466-4ff7-b849-96b8c7f6efe8.png)
