### ISSUE TITLE
Leave network

### ISSUE THREAD

**Issue by axesta** [jlama/powertagd#11]
I can see that the functionality for leaving a network is not implemented yet so do you have any tips on how to actually un-pair a powertag once it is paired with your solution? I don't have a gateway so I cannot go that route. Power-cycle it a few times? If so, how many? I tried power-cycling it a couple of times (4-5) but it seems to still be associated with the network created with powertagd. I have an R9M20 if that helps.

**Comment by jlama** [comment]
If the PowerTag cannot contact the gateway/powertagd for about 10min, it will start blinking red rapidly and after power-cycling can be paired with another device.

**Comment by axesta** [comment]
I finally had some time over to test some more and that actually seemed to do the trick, thanks for the tip!
