### ISSUE TITLE
Support for EFR32MG13 based devices

### ISSUE THREAD

**Issue by NicolaiPetri** [jlama/powertagd#13]
Hi, 
Just a questions - do you know hard it would be to support EFR32MG13 based devices ? 
I have the [POPP ZB-Stick (Zigbee) device.
Thanks,
Nicolai

**Comment by jlama** [comment]
Not trivial.
First step would be to reverse the pinout of the chip, i.e. which pins are connected to the UART.

**Comment by NicolaiPetri** [comment]
Ok. Thanks for the reply. 
Seems like it's not easily available, and I will simply just buy a supported adapter instead of the trouble.
