### ISSUE TITLE
[Question] Router mandatory ?

### ISSUE THREAD

**Issue by octera** [jlama/powertagd#2]
Hello,
Do we still need a dedicated router (like a philips hue light) with this firmware ? 
In others terms : can we run with only one sonoff dongle and multiple powertags?

Thanks

**Comment by jlama** [comment]
Yes this works without router. Using any router between the dongle and the PowerTags will very likely NOT work.

**Comment by octera** [comment]
If I understand well the router will cause issues in the time window for the dedicated ack needed by the powertag to keep him happy, right ?

**Comment by jlama** [comment]
Yes exactly. A router in-between will likely not relay the packet in time.
