### ISSUE TITLE
[Question] Choice of channel

### ISSUE THREAD

**Issue by octera** [jlama/powertagd#4]
Hello,
Maybe a dummy question : how to pick up the best channel ?

Here is my result of energy scan, but I don't know if I have to pick the one with higher or lower dBm ...

Starting energy scan...
Energy scan result: channel 11: -72 dBm
Energy scan result: channel 12: -73 dBm
Energy scan result: channel 13: -36 dBm
Energy scan result: channel 14: -33 dBm
Energy scan result: channel 15: -37 dBm
Energy scan result: channel 16: -50 dBm
Energy scan result: channel 17: -40 dBm
Energy scan result: channel 18: -40 dBm
Energy scan result: channel 19: -49 dBm
Energy scan result: channel 20: -50 dBm
Energy scan result: channel 21: -76 dBm
Energy scan result: channel 22: -79 dBm
Energy scan result: channel 23: -80 dBm
Energy scan result: channel 24: -80 dBm
Energy scan result: channel 25: -72 dBm
Energy scan result: channel 26: -27 dBm

Thanks

**Comment by jlama** [comment]
It's like Wifi, the higher the better. So channel 26 or 14 in your case.
