### ISSUE TITLE
Decryption Error?

### ISSUE THREAD

**Issue by Sany-IO** [jlama/powertagd#8]
Hello,

I have some Schneider Electric PowerTags and i become this message:

[code]
[INFO] tty: opening '/dev/ttyACM0' at 115200 bauds
[INFO] ash: connected to NCP
[INFO] ezsp: EZSPv9, stack type 2 (mesh), version 7.1.3.0
[INFO] ezsp: xNCP manufacturer: 0xbaba, version: 0x1000
[INFO] ezsp: registering gateway endpoint
[INFO] ezsp: registering Green Power endpoint
[INFO] ezsp: initializing network...
[INFO] ezsp: stack state changed to EMBER_NETWORK_UP
[INFO] ezsp: network joined as coordinator node on channel 24 (PAN: 0x690e, TX power: 0 dBm)
[WARN] gp: could not decrypt or validate GPF
[WARN] gp: could not decrypt or validate GPF

[/code]

**Comment by jlama** [comment]
This happens if a PowerTag was paired with another device. You need to re-pair the PowerTags with the dongle. To un-pair a PowerTag: power-off any coordinator/proxy and wait 5-10min for the PowerTag to blink red fast, then power-off the PowerTag.

**Comment by Sany-IO** [comment]
Thank you, the trick is wait 5-10 Minutes! ;)
